#Kush Parmar
#I pledge my honor that I have abided by the stevens honor system- Kush Parmar
CC = gcc -g
CFLAGS = -c -Wall

all: minishell.o
	$(CC) minishell.o -o a.out


minishell.o: minishell.c
	$(CC) minishell.c $(CFLAGS)

clean:
	rm *.o 